message(STATUS "Loading cmake module: AuroraFWBuild")
include(${CMAKE_MODULE_AURORAFW_DIR}/AuroraFWBuildConfig.cmake)
if(NOT DEFINED AURORAFW_IS_BUILDING)
	find_package(AuroraFWBuild)
endif()
message(STATUS "Loading cmake module: AuroraFW")
include(${CMAKE_MODULE_AURORAFW_DIR}/AuroraFWConfig.cmake)
if(NOT DEFINED AURORAFW_IS_BUILDING)
	find_package(AuroraFW)
endif()
install(FILES ${CMAKE_MODULE_AURORAFW_DIR}/AuroraFWBuildConfig.cmake DESTINATION share/cmake/AuroraFWBuild )
install(FILES ${CMAKE_MODULE_AURORAFW_DIR}/AuroraFWConfig.cmake DESTINATION share/cmake/AuroraFW )